# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [14]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])
a1.ndim

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[9,2,3],[5,2,3]])
a2.ndim

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[3,4,5]],[[12,3,4],[11,8,9]]])
a3.ndim
             

3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape , a1.size , a1.ndim , a1.dtype , type(a1)

((3,), 3, 1, dtype('int32'), numpy.ndarray)

In [18]:
# Attributes of 2-dimensional array
a2.shape , a2.ndim , a2.dtype , a2.size , type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [19]:
# Attributes of 3-dimensional array
a3.shape , a3.ndim , a3.dtype , a3.size , type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [24]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
array=pd.DataFrame(a2)
array

0  1  2
0  9  2  3
1  5  2  3

In [27]:
# Create an array of shape (10, 2) with only ones
ones=np.ones([10,2],dtype=np.int32)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [28]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros([7,2,3],dtype=np.int32)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [32]:
# Create an array within a range of 0 and 100 with step 3
arange=np.arange(0,100,3)
arange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [35]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randint_array=np.random.randint(10,size=(7,2))
randint_array

array([[1, 9],
       [7, 7],
       [9, 7],
       [8, 6],
       [3, 4],
       [7, 7],
       [1, 3]])

In [39]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array=np.random.random(size=(3,5))
random_array

array([[0.15063193, 0.34974944, 0.11178095, 0.66973702, 0.50630111],
       [0.9688202 , 0.44713124, 0.21683663, 0.04840397, 0.64020487],
       [0.27302203, 0.19224287, 0.72022487, 0.36252418, 0.47225519]])

In [42]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
randint_array2=np.random.randint(0,10,size=(4,6))
randint_array2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [50]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
randint_array3=np.random.randint(0,10,size=(3,7))
# and save it to a variable
a=randint_array3
a

# Find the unique numbers in the array you just created
# np.unique(a)

array([[5, 2, 0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8, 9, 9],
       [2, 6, 0, 3, 3, 4, 6]])

In [52]:
# Find the 0'th index of the latest array you created
randint_array3[0][0]

5

In [56]:
# Get the first 2 rows of latest array you created
randint_array3[:2][:]

array([[5, 2, 0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8, 9, 9]])

In [60]:
# Get the first 2 values of the first 2 rows of the latest array
randint_array3[:2,:1]

array([[5],
       [4]])

In [63]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array=np.random.randint(0,10,size=(3,5))
ones=np.ones([3,5])

In [ ]:
# Add the two arrays together
together_arrays=ones + array
together_arrays

In [68]:
together_arrays.shape

(3, 5)

In [65]:
# Create another array of ones of shape (5, 3)
ones2=np.ones([5,3])


In [70]:
# Try add the array of ones and the other most recent array together
total_array=together_arrays.T + ones2
total_array

array([[ 2., 10., 10.],
       [ 2.,  4.,  6.],
       [10.,  8.,  2.],
       [10.,  7.,  4.],
       [ 5.,  9., 11.]])

When you try the last cell, it produces an error. Why do think this is?
because they have not same shape ones2 shape=(5,3) and addition the two array have shape (3,5)
How would you fix it?
we should use T to one of the arrays that we want do addition

In [71]:
# Create another array of ones of shape (3, 5)
ones3=np.ones([3,5])

In [73]:
# Subtract the new array of ones from the other most recent array
array_subtract=total_array - ones3.T

In [76]:
# Multiply the ones array with the latest array
Multiple_array=total_array.T * ones3
Multiple_array

array([[ 2.,  2., 10., 10.,  5.],
       [10.,  4.,  8.,  7.,  9.],
       [10.,  6.,  2.,  4., 11.]])

In [78]:
# Take the latest array to the power of 2 using '**'
power_by_2=Multiple_array**2
power_by_2

array([[  4.,   4., 100., 100.,  25.],
       [100.,  16.,  64.,  49.,  81.],
       [100.,  36.,   4.,  16., 121.]])

In [80]:
# Do the same thing with np.square()
square=np.square(Multiple_array)
square

array([[  4.,   4., 100., 100.,  25.],
       [100.,  16.,  64.,  49.,  81.],
       [100.,  36.,   4.,  16., 121.]])

In [82]:
# Find the mean of the latest array using np.mean()
averag=Multiple_array.mean()
averag

6.666666666666667

In [84]:
# Find the maximum of the latest array using np.max()
Max=Multiple_array.max()
Max


11.0

In [86]:
# Find the minimum of the latest array using np.min()
Min=Multiple_array.min()
Min

2.0

In [88]:
# Find the standard deviation of the latest array
std=Multiple_array.std()
std

3.197221015541813

In [90]:
# Find the variance of the latest array
Var=Multiple_array.var()
Var

10.222222222222223

In [93]:
# Reshape the latest array to (3, 5, 1)
Reshape_array=ones3.reshape(3,5,1)

In [97]:
# Transpose the latest array
Reshape_array.T

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

What does the transpose do?
transpose do make clumn line and line column 

In [100]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1=np.random.randint(0,10,size=(3,3))
array2=np.random.randint(0,10,size=(3,2))

In [106]:
# Perform a dot product on the two newest arrays you created
array2=array2.T
dot_product=np.dot(array1,array2)

In [108]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array3=np.random.randint(0,10,size=(4,3))
array4=np.random.randint(0,10,size=(4,3))

In [109]:
# Perform a dot product on the two newest arrays you created
dot_product2=array3.dot(array4.T)

It doesn't work. How would you fix it?
i have to Transport one of this matrix

In [110]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
array4=array4.T
dot_product=array3.dot(array4)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [113]:
# Create two arrays of random integers between 0 & 10 of the same shape
array5=np.random.randint(0,10,size=(4,3))
array6=np.random.randint(0,10,size=(4,3))

# and save them to variables


In [114]:
# Compare the two arrays with '>'
array5 > array6

array([[False,  True, False],
       [ True, False, False],
       [False,  True,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [115]:
# Compare the two arrays with '>='
array5 >= array6

array([[False,  True, False],
       [ True, False, False],
       [False,  True,  True],
       [ True,  True, False]])

In [120]:
# Find which elements of the first array are greater than 7



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.