<a href="https://colab.research.google.com/github/achraf-bogryn/ML-repository/blob/main/Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pytorch Fundamental
####Resource Notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/#introduction-to-tensors

####Repository : https://github.com/mrdbourke/pytorch-deep-learning/tree/main

In [ ]:
print("hello I'm execited")

hello I'm execited


In [ ]:
!nvidia-smi

Tue May  7 21:52:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print (torch.__version__)

2.2.1+cu121


##Introduction Tensors
###Creating Tensors



In [ ]:
#Scalar
scalar = torch.tensor(100)
scalar

tensor(100)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

100

In [ ]:
#Vector
vector = torch.tensor([10,8]);
vector

tensor([10,  8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
Matrix = torch.tensor([[19,90,2],[20,9,25]])
Matrix

tensor([[19, 90,  2],
        [20,  9, 25]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([2, 3])

In [ ]:
random=torch.rand(size=(255,255,3))
random

tensor([[[0.3672, 0.2036, 0.8282],
         [0.3707, 0.0894, 0.8296],
         [0.2517, 0.9976, 0.6036],
         ...,
         [0.0656, 0.1403, 0.5911],
         [0.1137, 0.6242, 0.3276],
         [0.9108, 0.2921, 0.8802]],

        [[0.0314, 0.2578, 0.8027],
         [0.7245, 0.3049, 0.4091],
         [0.9051, 0.2272, 0.1347],
         ...,
         [0.0100, 0.8588, 0.9750],
         [0.1842, 0.9569, 0.4347],
         [0.5704, 0.5491, 0.4055]],

        [[0.4473, 0.4276, 0.7709],
         [0.6702, 0.8604, 0.3508],
         [0.4835, 0.2576, 0.6279],
         ...,
         [0.6253, 0.6588, 0.9130],
         [0.5351, 0.3926, 0.7527],
         [0.2962, 0.8661, 0.8505]],

        ...,

        [[0.2649, 0.8651, 0.2535],
         [0.1304, 0.4810, 0.5921],
         [0.5066, 0.9750, 0.5483],
         ...,
         [0.9675, 0.3650, 0.2027],
         [0.4759, 0.4544, 0.2867],
         [0.7244, 0.4695, 0.8410]],

        [[0.2158, 0.3663, 0.9033],
         [0.7687, 0.5927, 0.3303],
         [0.

In [ ]:
random.shape

torch.Size([255, 255, 3])

In [ ]:
random.ndim

3

In [ ]:
random.dtype

torch.float32

In [ ]:
random*100

tensor([[[36.7193, 20.3595, 82.8226],
         [37.0652,  8.9360, 82.9593],
         [25.1654, 99.7639, 60.3576],
         ...,
         [ 6.5605, 14.0319, 59.1139],
         [11.3749, 62.4226, 32.7553],
         [91.0848, 29.2123, 88.0203]],

        [[ 3.1404, 25.7757, 80.2719],
         [72.4529, 30.4861, 40.9058],
         [90.5135, 22.7222, 13.4675],
         ...,
         [ 1.0048, 85.8775, 97.4965],
         [18.4173, 95.6921, 43.4696],
         [57.0445, 54.9054, 40.5460]],

        [[44.7283, 42.7579, 77.0943],
         [67.0166, 86.0380, 35.0764],
         [48.3497, 25.7605, 62.7866],
         ...,
         [62.5263, 65.8818, 91.2959],
         [53.5112, 39.2586, 75.2660],
         [29.6176, 86.6078, 85.0515]],

        ...,

        [[26.4941, 86.5132, 25.3466],
         [13.0351, 48.1026, 59.2129],
         [50.6556, 97.5048, 54.8334],
         ...,
         [96.7478, 36.4956, 20.2713],
         [47.5899, 45.4419, 28.6710],
         [72.4376, 46.9530, 84.0993]],

        [[

In [ ]:
random=random.to(torch.int32)
random.dtype

torch.int32

In [ ]:
ZERO=torch.zeros(size=(3,3))
ZERO
ZERO.dtype

torch.float32

In [ ]:
ONES=torch.ones(size=(3,3))
ONES
ONES.dtype

torch.float32

In [ ]:
zero_to_ten_rang=torch.range(0,10)
zero_to_ten_rang

<ipython-input-41-dbf8ea886e04>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_rang=torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
zero_to_ten_aange=torch.arange(start=1,end=11,step=1)
zero_to_ten_aange

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.1368, 0.8443, 0.1277, 0.6208],
        [0.6052, 0.3253, 0.0464, 0.7171],
        [0.9764, 0.3846, 0.6625, 0.3528]])

In [ ]:
some_tensor.dtype , some_tensor.shape , some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

In [ ]:
torch.mul(some_tensor,10)

tensor([[1.3680, 8.4426, 1.2768, 6.2076],
        [6.0520, 3.2529, 0.4645, 7.1711],
        [9.7637, 3.8460, 6.6249, 3.5277]])

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
filter=torch.rand(4,3)
filter

tensor([[0.3989, 0.6335, 0.6120],
        [0.1516, 0.9492, 0.5705],
        [0.6144, 0.6575, 0.4515],
        [0.3900, 0.9895, 0.0627]])

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
torch.matmul(filter,some_tensor)

tensor([[1.0355, 0.7782, 0.4858, 0.9178],
        [1.1522, 0.6562, 0.4414, 0.9760],
        [0.9228, 0.9062, 0.4081, 1.0121],
        [0.7134, 0.6752, 0.1373, 0.9738]])

In [ ]:
matrix_a=torch.rand(3,4)
matrix_b=torch.rand(3,4)

In [ ]:
matrix_a

tensor([[0.4176, 0.3944, 0.1736, 0.5939],
        [0.4966, 0.9887, 0.7306, 0.0641],
        [0.2534, 0.6092, 0.2099, 0.7395]])

In [ ]:
matrix_b , matrix_b.T

(tensor([[0.6756, 0.0932, 0.1864, 0.7331],
         [0.4758, 0.3003, 0.7399, 0.2406],
         [0.8039, 0.8626, 0.8065, 0.4238]]),
 tensor([[0.6756, 0.4758, 0.8039],
         [0.0932, 0.3003, 0.8626],
         [0.1864, 0.7399, 0.8065],
         [0.7331, 0.2406, 0.4238]]))

In [ ]:
torch.matmul(matrix_a,matrix_b.T)

tensor([[1.2264, 1.3899, 2.3046],
        [0.4501, 0.5272, 0.9733],
        [0.7285, 0.6217, 1.3228]])

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print (torch.__version__)

a=torch.tensor([[1,2,3],
                       [5,6,7],
                       [8,9,10]],dtype=torch.float16)
a


2.2.1+cu121


tensor([[ 1.,  2.,  3.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], dtype=torch.float16)

In [ ]:
torch.manual_seed(42)
linear=torch.nn.Linear(in_features=2,out_features=6)
# Option 1: Cast the input tensor to the same data type as the weights and biases of the linear module
x = x.float()
output = linear(x)

# Option 2: Cast the weights and biases of the linear module to the same data type as the input tensor
linear.weight.data = linear.weight.data.float()
linear.bias.data = linear.bias.data.float()
output = linear(x)
# x=a
output=linear(x)
output
linear

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x6)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=5) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.3290,  1.2658,  0.6529,  0.5820, -0.0732],
        [ 4.5841,  2.2336,  0.6284,  0.7241,  0.1360],
        [ 6.8391,  3.2014,  0.6039,  0.8661,  0.3452]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 5])
